# Generated by Django 5.2.3 on 2025-06-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quilometragem Atual (km)')),
                ('consumo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Consumo Total (litros)')),
                ('media_consumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Média de Consumo (km/l)')),
            ],
            options={
                'verbose_name': 'Caminhão',
                'verbose_name_plural': 'Caminhões',
            },
        ),
        migrations.AddField(
            model_name='motorista',
            name='combustivel_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Combustível Total (litros)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='media_consumo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Média de Consumo (km/l)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='quilometragem_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quilometragem (km)'),
        ),
    ]
