# Generated by Django 5.2.3 on 2025-06-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0002_caminhao_motorista_combustivel_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='ano',
            field=models.PositiveIntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='marca',
            field=models.CharField(default='Desconhecida', max_length=50),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='modelo',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
