# Generated by Django 5.2.3 on 2025-06-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0003_alter_caminhao_ano_alter_caminhao_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='marca',
            field=models.CharField(default='Volvo', max_length=50),
        ),
    ]
