# Generated by Django 5.2.3 on 2025-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0004_alter_caminhao_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='media_consumo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Média de Consumo (km/l)'),
        ),
    ]
