# Generated by Django 5.2.3 on 2025-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0005_alter_motorista_media_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='combustivel_total',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Combustível Total (litros)'),
        ),
    ]
