# Generated by Django 5.2.3 on 2025-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0006_alter_motorista_combustivel_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caminhao',
            name='consumo_total',
        ),
        migrations.AddField(
            model_name='caminhao',
            name='combustivel_total',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Combustível Total (litros)'),
        ),
    ]
