# Generated by Django 5.2.3 on 2025-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0007_remove_caminhao_consumo_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caminhao',
            old_name='combustivel_total',
            new_name='Consumido',
        ),
        migrations.RenameField(
            model_name='caminhao',
            old_name='media_consumo',
            new_name='Quilometragem_média',
        ),
        migrations.RenameField(
            model_name='caminhao',
            old_name='placa',
            new_name='agrupamento',
        ),
        migrations.RenameField(
            model_name='caminhao',
            old_name='quilometragem_atual',
            new_name='quilometragem',
        ),
        migrations.RemoveField(
            model_name='caminhao',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='caminhao',
            name='modelo',
        ),
        migrations.AddField(
            model_name='caminhao',
            name='Emissões_CO2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Emissões de CO2 (g/km)'),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='Horas_de_motor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Horas de Motor'),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='RPM_médio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='RPM Médio do Motor'),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='Temperatura_média',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Temperatura Média (°C)'),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='Velocidade_média',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Velocidade Média (km/h)'),
        ),
    ]
