# Generated by Django 5.2.3 on 2025-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0008_rename_combustivel_total_caminhao_consumido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='Consumido',
            field=models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='Combustível Total (litros)'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='Emissões_CO2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Emissões de CO2 (g/km)'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='Horas_de_motor',
            field=models.CharField(blank=True, default=0.0, max_length=100, null=True, verbose_name='Horas de Motor'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='Quilometragem_média',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='RPM_médio',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='RPM Médio do Motor'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='Temperatura_média',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Temperatura Média (°C)'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='Velocidade_média',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Velocidade Média (km/h)'),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='quilometragem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem Atual (km)'),
        ),
    ]
