# Generated by Django 5.2.3 on 2025-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0009_alter_caminhao_consumido_alter_caminhao_emissões_co2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='combustivel_total',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='media_consumo',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='quilometragem_total',
        ),
        migrations.AddField(
            model_name='motorista',
            name='Consumido',
            field=models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='Combustível Total (litros)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='Emissões_CO2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Emissões de CO2 (g/km)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='Horas_de_motor',
            field=models.CharField(blank=True, default=0.0, max_length=100, null=True, verbose_name='Horas de Motor'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='Quilometragem_média',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='Velocidade_média',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Velocidade Média (km/h)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='quilometragem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem Atual (km)'),
        ),
    ]
