# Generated by Django 5.2.3 on 2025-06-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0010_remove_motorista_combustivel_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='nome',
            new_name='agrupamento',
        ),
    ]
