# Generated by Django 5.2.3 on 2025-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0011_rename_nome_motorista_agrupamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumido_total', models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='Combustível Total (litros)')),
                ('Quilometragem_média', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)')),
                ('Velocidade_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Velocidade Média (km/h)')),
                ('RPM_médio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='RPM Médio do Motor')),
                ('Temperatura_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Temperatura Média (°C)')),
                ('Emissões_CO2_total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Emissões de CO2 (g/km)')),
                ('numero_motoristas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número de Motoristas')),
                ('numero_caminhoes', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número de Caminhões')),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
            },
        ),
    ]
