# Generated by Django 5.2.3 on 2025-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella360', '0012_calculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo_Scania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometragem', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem Atual (km)')),
                ('Consumido', models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='Combustível Total (litros)')),
                ('Quilometragem_média', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)')),
                ('Velocidade_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Velocidade Média (km/h)')),
                ('RPM_médio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='RPM Médio do Motor')),
                ('Temperatura_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Temperatura Média (°C)')),
                ('Emissões_CO2', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Emissões de CO2 (g/km)')),
            ],
        ),
        migrations.CreateModel(
            name='Calculo_Volvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometragem', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quilometragem Atual (km)')),
                ('Consumido', models.PositiveIntegerField(blank=True, default=0.0, null=True, verbose_name='Combustível Total (litros)')),
                ('Quilometragem_média', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Média de Consumo (km/l)')),
                ('Velocidade_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Velocidade Média (km/h)')),
                ('RPM_médio', models.FloatField(blank=True, default=0.0, null=True, verbose_name='RPM Médio do Motor')),
                ('Temperatura_média', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Temperatura Média (°C)')),
                ('Emissões_CO2', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Emissões de CO2 (g/km)')),
            ],
        ),
        migrations.DeleteModel(
            name='Calculo',
        ),
    ]
